name: beanswithbeans
favicon: null
layout_spectrum: 0.49785
typography_spectrum: 0.73526
title: 'Beans with beans!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#040404'
    - '#d0d4d5'
    - '#acaaab'
    - '#464445'
  brandStrength: 0.3125
  lightness: 0.5625
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
