name: beanswithbeans
favicon: null
layout_spectrum: 0.88698
typography_spectrum: 0.73526
title: 'Beans with beans!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#190812'
    - '#d1b091'
    - '#87654a'
    - '#ddd2cc'
    - '#4e311f'
  brandStrength: 0.125
  lightness: 0.3125
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
